FROM jenkins/jnlp-slave:latest

# Install Git, kubectl, and Helm CLI
USER root

RUN apt-get update && apt-get install -y git kubectl && \
    curl -fsSL -o /usr/local/bin/helm https://get.helm.sh/helm-v3.7.0-linux-amd64 && \
    chmod +x /usr/local/bin/helm
RUN mkdir -p /home/jenkins/.kube
WORKDIR /home/jenkins
# Switch back to the Jenkins user
USER jenkins